In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [12]:
obesity_df = pd.read_csv('../data/Behavioral_Risk_Factor_Surveillance_System__BRFSS__Prevalence_Data__2011_to_present_.csv')

In [13]:
obesity_df.head()

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
0,2012,GU,Guam,Demographics,Age,What is your age?,55-64 years,Overall,Overall,296,...,NaN,BRFSS,CLASS05,Topic02,66,BO1,CAT1,AGE,RESP014,"(13.444304, 144.793731)"
1,2012,GU,Guam,Demographics,Age,What is your age?,35-44 years,Female,Gender,272,...,NaN,BRFSS,CLASS05,Topic02,66,SEX2,CAT2,AGE,RESP012,"(13.444304, 144.793731)"
2,2013,GU,Guam,Health Status,Overall Health,How is your general health?,Excellent,18-24,Age Group,69,...,NaN,BRFSS,CLASS08,Topic41,66,AGE01,CAT3,GENHLTH,RESP056,"(13.444304, 144.793731)"
3,2013,GU,Guam,Demographics,Marital Status,What is your marital status?,Partnered,H.S. or G.E.D.,Education Attained,48,...,NaN,BRFSS,CLASS05,Topic38,66,EDUCA2,CAT5,MARITAL,RESP038,"(13.444304, 144.793731)"
4,2013,PR,Puerto Rico,Demographics,Age,What is your age?,25-34 years,Some post-H.S.,Education Attained,183,...,NaN,BRFSS,CLASS05,Topic02,72,EDUCA3,CAT5,AGE,RESP011,"(18.220833, -66.590149)"

In [28]:
is_overweight = obesity_df['Class'] == 'Overweight and Obesity (BMI)'
is_overweight
#filtering down to rows that deal with obesity

0          False
1          False
2          False
3          False
4          False
           ...
1827487    False
1827488    False
1827489    False
1827490    False
1827491    False
Name: Class, Length: 1827492, dtype: bool

In [32]:
obesity_df_2019 = obesity_df[is_overweight]
obesity_df_2019

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
46,2019,KY,Kentucky,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),Overall,Overall,2706,...,NaN,BRFSS,CLASS14,TOPIC09,21,BO1,CAT1,_BMI5CAT,RESP040,"(37.645970271000465, -84.77497104799966)"
125,2019,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Overall,Overall,859,...,NaN,BRFSS,CLASS14,TOPIC09,2,BO1,CAT1,_BMI5CAT,RESP041,"(64.84507995700051, -147.72205903599973)"
126,2019,AK,Alaska,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Male,Gender,353,...,NaN,BRFSS,CLASS14,TOPIC09,2,SEX1,CAT2,_BMI5CAT,RESP041,"(64.84507995700051, -147.72205903599973)"
533,2019,ID,Idaho,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Overall,Overall,1608,...,NaN,BRFSS,CLASS14,TOPIC09,16,BO1,CAT1,_BMI5CAT,RESP041,"(43.682630005000476, -114.3637300419997)"
534,2019,ID,Idaho,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Underweight (BMI 12.0-18.4),Male,Gender,28,...,NaN,BRFSS,CLASS14,TOPIC09,16,SEX1,CAT2,_BMI5CAT,RESP042,"(43.682630005000476, -114.3637300419997)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827236,2018,PR,Puerto Rico,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),"Multiracial, non-Hispanic",Race/Ethnicity,1,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS14,TOPIC09,72,RACE07,CAT4,_BMI5CAT,RESP041,"(18.220833, -66.590149)"
1827253,2018,GU,Guam,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),25-34,Age Group,66,...,NaN,BRFSS,CLASS14,TOPIC09,66,AGE02,CAT3,_BMI5CAT,RESP040,"(13.444304, 144.793731)"
1827258,2018,WI,Wisconsin,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),25-34,Age Group,145,...,NaN,BRFSS,CLASS14,TOPIC09,55,AGE02,CAT3,_BMI5CAT,RESP040,"(44.39319117400049, -89.81637074199966)"
1827307,2018,WI,Wisconsin,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),"American Indian or Alaskan Native, non-Hispanic",Race/Ethnicity,37,...,NaN,BRFSS,CLASS14,TOPIC09,55,RACE03,CAT4,_BMI5CAT,RESP040,"(44.39319117400049, -89.81637074199966)"
1827409,2018,WI,Wisconsin,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Male,Gender,510,...,NaN,BRFSS,CLASS14,TOPIC09,55,SEX1,CAT2,_BMI5CAT,RESP041,"(44.39319117400049, -89.81637074199966)"

In [31]:
obesity_df_2019.shape

(47074, 27)