In [2]:
import pandas as pd 
import numpy as np

In [3]:
cdc_data = pd.read_csv('../data/pppub19.csv')
cdc_data_2 = pd.read_csv('../data/asec_csv_repwgt_2019.csv')

In [4]:
cdc_data.head()

,PERIDNUM,GESTCEN,PH_SEQ,GTCBSA,P_SEQ,A_LINENO,PF_SEQ,PHF_SEQ,OED_TYP1,OED_TYP2,...,I_DISVL1,I_DISVL2,I_SURVL1,I_SURVL2,MIG_CBST,MIG_DSCP,DEP_STAT,FILEDATE,FILESTAT,MMYY
0,0100069124539430801101,11,4,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,110419,5,32019
1,3999403901610020901101,11,6,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,110419,5,32019
2,9119340093206090901101,11,7,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,110419,5,32019
3,1410320300969990901101,11,8,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,110419,6,32019
4,1410320300969990901102,11,8,0,2,2,1,1,0,0,...,0,0,0,0,0,0,0,110419,5,32019

In [5]:
cdc_data_2.shape

(180101, 163)