In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [21]:
obesity_df = pd.read_csv('../data/Behavioral_Risk_Factor_Surveillance_System__BRFSS__Prevalence_Data__2011_to_present_.csv')

In [22]:
obesity_df.head()

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
0,2012,GU,Guam,Demographics,Age,What is your age?,55-64 years,Overall,Overall,296,...,NaN,BRFSS,CLASS05,Topic02,66,BO1,CAT1,AGE,RESP014,"(13.444304, 144.793731)"
1,2012,GU,Guam,Demographics,Age,What is your age?,35-44 years,Female,Gender,272,...,NaN,BRFSS,CLASS05,Topic02,66,SEX2,CAT2,AGE,RESP012,"(13.444304, 144.793731)"
2,2013,GU,Guam,Health Status,Overall Health,How is your general health?,Excellent,18-24,Age Group,69,...,NaN,BRFSS,CLASS08,Topic41,66,AGE01,CAT3,GENHLTH,RESP056,"(13.444304, 144.793731)"
3,2013,GU,Guam,Demographics,Marital Status,What is your marital status?,Partnered,H.S. or G.E.D.,Education Attained,48,...,NaN,BRFSS,CLASS05,Topic38,66,EDUCA2,CAT5,MARITAL,RESP038,"(13.444304, 144.793731)"
4,2013,PR,Puerto Rico,Demographics,Age,What is your age?,25-34 years,Some post-H.S.,Education Attained,183,...,NaN,BRFSS,CLASS05,Topic02,72,EDUCA3,CAT5,AGE,RESP011,"(18.220833, -66.590149)"

In [23]:
obesity_df.columns

Index(['Year', 'Locationabbr', 'Locationdesc', 'Class', 'Topic', 'Question',
       'Response', 'Break_Out', 'Break_Out_Category', 'Sample_Size',
       'Data_value', 'Confidence_limit_Low', 'Confidence_limit_High',
       'Display_order', 'Data_value_unit', 'Data_value_type',
       'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'DataSource',
       'ClassId', 'TopicId', 'LocationID', 'BreakoutID', 'BreakOutCategoryID',
       'QuestionID', 'ResponseID', 'GeoLocation'],
      dtype='object')

In [24]:
obesity_df_2019.shape

(47074, 27)

In [32]:
race_ethinicity_df  = obesity_df[obesity_df['Break_Out_Category'].isin(['Race/Ethnicity'])]

In [31]:
age_df = obesity_df[obesity_df['Break_Out_Category'].isin(['Age Group'])]
age_df

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
2,2013,GU,Guam,Health Status,Overall Health,How is your general health?,Excellent,18-24,Age Group,69,...,NaN,BRFSS,CLASS08,Topic41,66,AGE01,CAT3,GENHLTH,RESP056,"(13.444304, 144.793731)"
6,2011,GU,Guam,Demographics,Employment,What is your employment status?,Homemkr,65+,Age Group,19,...,NaN,BRFSS,CLASS05,Topic22,66,AGE09,CAT3,EMPLOY,RESP029,"(13.444304, 144.793731)"
7,2019,KS,Kansas,Health Care Access/Coverage,Last Checkup,About how long has it been since you last visi...,Within the past year,45-54,Age Group,1235,...,NaN,BRFSS,CLASS07,TOPIC36,20,AGE04,CAT3,CHECKUP1,RESP063,"(38.34774030000045, -98.20078122699965)"
9,2013,GU,Guam,Immunization,Tetanus Shot,"Since 2005, have you had a tetanus shot?",No,25-34,Age Group,109,...,NaN,BRFSS,CLASS11,Topic58,66,AGE02,CAT3,TETANUS,RESP054,"(13.444304, 144.793731)"
10,2011,GU,Guam,Chronic Health Indicators,Vision,Ever told you have vision impairment?,No,65+,Age Group,135,...,NaN,BRFSS,CLASS03,Topic62,66,AGE09,CAT3,CHCVISON,RESP054,"(13.444304, 144.793731)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827468,2018,WI,Wisconsin,Health Status,Overall Health,How is your general health?,Poor,35-44,Age Group,17,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS08,TOPIC41,55,AGE03,CAT3,GENHLTH,RESP060,"(44.39319117400049, -89.81637074199966)"
1827469,2018,GU,Guam,Injury,Drink and Drive,Respondents who have reported having driven af...,Have driven after having too much to drink,45-54,Age Group,7,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS12,TOPIC20,66,AGE04,CAT3,_DRNKDRV,RESP201,"(13.444304, 144.793731)"
1827470,2018,WY,Wyoming,Immunization,Flu Shot,Adults aged 65+ who have had a flu shot within...,No,75+,Age Group,303,...,NaN,BRFSS,CLASS11,TOPIC26,56,AGE11,CAT3,_FLSHOT6,RESP054,"(43.23554134300048, -108.10983035299967)"
1827481,2018,GU,Guam,HIV-AIDS,HIV Test,Have you ever been tested for HIV?,No,18-24,Age Group,98,...,NaN,BRFSS,CLASS09,TOPIC32,66,AGE01,CAT3,HIVTST6,RESP054,"(13.444304, 144.793731)"
1827489,2018,GU,Guam,Demographics,Race,What is your race/ethnicity?,"Black, non-Hispanic",35-44,Age Group,4,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS05,TOPIC48,66,AGE03,CAT3,RACE8,RESP195,"(13.444304, 144.793731)"

In [30]:
income_df = obesity_df[obesity_df['Break_Out_Category'].isin(['Household Income'])]
income_df

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
11,2011,GU,Guam,Demographics,Age,What is your age?,45-54 years,"$15,000-$24,999",Household Income,46,...,NaN,BRFSS,CLASS05,Topic02,66,INCOME2,CAT6,AGE,RESP013,"(13.444304, 144.793731)"
39,2019,KY,Kentucky,Demographics,Hearing,Adults who reported being deaf,Yes,"$50,000+",Household Income,205,...,NaN,BRFSS,CLASS05,TOPIC70,21,INCOME5,CAT6,DEAF,RESP046,"(37.645970271000465, -84.77497104799966)"
53,2019,LA,Louisiana,Chronic Health Indicators,Skin Cancer,Ever told you had skin cancer?,No,"$35,000-$49,999",Household Income,451,...,NaN,BRFSS,CLASS03,TOPIC53,22,INCOME4,CAT6,CHCSCNCR,RESP054,"(31.31266064400046, -92.44568007099969)"
72,2011,GU,Guam,Demographics,Employment,What is your employment status?,Retired,"$35,000-$49,999",Household Income,29,...,NaN,BRFSS,CLASS05,Topic22,66,INCOME4,CAT6,EMPLOY,RESP031,"(13.444304, 144.793731)"
74,2019,AL,Alabama,Demographics,Hearing,Adults who reported being deaf,No,"Less than $15,000",Household Income,637,...,NaN,BRFSS,CLASS05,TOPIC70,1,INCOME1,CAT6,DEAF,RESP054,"(32.84057112200048, -86.63186076199969)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827482,2018,PR,Puerto Rico,Chronic Health Indicators,Asthma,Adults who have been told they currently have ...,Yes,"$50,000+",Household Income,27,...,NaN,BRFSS,CLASS03,TOPIC06,72,INCOME5,CAT6,_CASTHM1,RESP046,"(18.220833, -66.590149)"
1827484,2018,WY,Wyoming,Physical Activity,Exercise,"During the past month, did you participate in ...",Yes,"$50,000+",Household Income,1618,...,NaN,BRFSS,CLASS15,TOPIC23,56,INCOME5,CAT6,_TOTINDA,RESP046,"(43.23554134300048, -108.10983035299967)"
1827485,2018,PR,Puerto Rico,Tobacco Use,Smokeless Tobacco,"Do you currently use chewing tobacco, snuff, o...",Some days,"$15,000-$24,999",Household Income,6,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS17,TOPIC54,72,INCOME2,CAT6,USENOW3,RESP080,"(18.220833, -66.590149)"
1827490,2018,WY,Wyoming,Demographics,Employment,What is your employment status?,Retired,"$25,000-$34,999",Household Income,177,...,NaN,BRFSS,CLASS05,TOPIC22,56,INCOME3,CAT6,EMPLOY1,RESP031,"(43.23554134300048, -108.10983035299967)"
1827491,2018,GU,Guam,Chronic Health Indicators,Skin Cancer,Ever told you had skin cancer?,No,"$15,000-$24,999",Household Income,251,...,NaN,BRFSS,CLASS03,TOPIC53,66,INCOME2,CAT6,CHCSCNCR,RESP054,"(13.444304, 144.793731)"

In [33]:
education_df = obesity_df[obesity_df['Break_Out_Category'].isin(['Education Attained'])]
education_df

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
3,2013,GU,Guam,Demographics,Marital Status,What is your marital status?,Partnered,H.S. or G.E.D.,Education Attained,48,...,NaN,BRFSS,CLASS05,Topic38,66,EDUCA2,CAT5,MARITAL,RESP038,"(13.444304, 144.793731)"
4,2013,PR,Puerto Rico,Demographics,Age,What is your age?,25-34 years,Some post-H.S.,Education Attained,183,...,NaN,BRFSS,CLASS05,Topic02,72,EDUCA3,CAT5,AGE,RESP011,"(18.220833, -66.590149)"
12,2013,GU,Guam,Health Status,Overall Health,How is your general health?,Poor,Less than H.S.,Education Attained,24,...,NaN,BRFSS,CLASS08,Topic41,66,EDUCA1,CAT5,GENHLTH,RESP060,"(13.444304, 144.793731)"
20,2019,KY,Kentucky,Chronic Health Indicators,Asthma,Adults who have ever been told they have asthm...,Yes,College graduate,Education Attained,301,...,NaN,BRFSS,CLASS03,TOPIC06,21,EDUCA4,CAT5,_LTASTH1,RESP046,"(37.645970271000465, -84.77497104799966)"
22,2019,KY,Kentucky,Chronic Health Indicators,COPD,Ever told you have COPD?,Yes,College graduate,Education Attained,142,...,NaN,BRFSS,CLASS03,TOPIC14,21,EDUCA4,CAT5,CHCCOPD2,RESP046,"(37.645970271000465, -84.77497104799966)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827459,2018,WY,Wyoming,Demographics,Income,What is your annual household income?,"$50,000+",H.S. or G.E.D.,Education Attained,384,...,NaN,BRFSS,CLASS05,TOPIC33,56,EDUCA2,CAT5,INCOME,RESP020,"(43.23554134300048, -108.10983035299967)"
1827460,2018,PR,Puerto Rico,Demographics,Disability status,Are you blind or do you have serious difficult...,Yes,Less than H.S.,Education Attained,223,...,NaN,BRFSS,CLASS05,TOPIC19,72,EDUCA1,CAT5,BLIND,RESP046,"(18.220833, -66.590149)"
1827478,2018,PR,Puerto Rico,Injury,Drink and Drive,Respondents who have reported having driven af...,Have not driven after having too much to drink,Less than H.S.,Education Attained,125,...,NaN,BRFSS,CLASS12,TOPIC20,72,EDUCA1,CAT5,_DRNKDRV,RESP202,"(18.220833, -66.590149)"
1827479,2018,WY,Wyoming,Chronic Health Indicators,Cardiovascular Disease,Ever told you had angina or coronary heart dis...,Yes,Less than H.S.,Education Attained,15,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS03,TOPIC10,56,EDUCA1,CAT5,CVDCRHD4,RESP046,"(43.23554134300048, -108.10983035299967)"
1827488,2018,GU,Guam,Demographics,Race,What is your race/ethnicity?,"Other race, non-Hispanic",Some post-H.S.,Education Attained,7,...,Prevalence estimate not available if the unwei...,BRFSS,CLASS05,TOPIC48,66,EDUCA3,CAT5,RACE8,RESP199,"(13.444304, 144.793731)"

In [29]:
gender_df =obesity_df[obesity_df['Break_Out_Category'].isin(['Gender'])]
gender_df

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
1,2012,GU,Guam,Demographics,Age,What is your age?,35-44 years,Female,Gender,272,...,NaN,BRFSS,CLASS05,Topic02,66,SEX2,CAT2,AGE,RESP012,"(13.444304, 144.793731)"
15,2013,GA,Georgia,Demographics,Race,What is your race/ethnicity?,White,Male,Gender,2016,...,NaN,BRFSS,CLASS05,Topic48,13,SEX1,CAT2,RACE,RESP005,"(32.839681093, -83.627580346)"
16,2019,KS,Kansas,Tobacco Use,Smokeless Tobacco,"Do you currently use chewing tobacco, snuff, o...",Some days,Female,Gender,17,...,NaN,BRFSS,CLASS17,TOPIC54,20,SEX2,CAT2,USENOW3,RESP080,"(38.34774030000045, -98.20078122699965)"
19,2011,ND,North Dakota,Chronic Health Indicators,Vision,Ever told you have vision impairment?,No,Male,Gender,1823,...,NaN,BRFSS,CLASS03,Topic62,38,SEX1,CAT2,CHCVISON,RESP054,"(47.475319779, -100.118421049)"
21,2019,KY,Kentucky,Chronic Health Indicators,Cardiovascular Disease,Ever told you had a heart attack (myocardial i...,No,Female,Gender,4195,...,NaN,BRFSS,CLASS03,TOPIC10,21,SEX2,CAT2,CVDINFR4,RESP054,"(37.645970271000465, -84.77497104799966)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827409,2018,WI,Wisconsin,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Normal Weight (BMI 18.5-24.9),Male,Gender,510,...,NaN,BRFSS,CLASS14,TOPIC09,55,SEX1,CAT2,_BMI5CAT,RESP041,"(44.39319117400049, -89.81637074199966)"
1827433,2018,PR,Puerto Rico,Demographics,Marital Status,What is your marital status?,Separated,Female,Gender,116,...,NaN,BRFSS,CLASS05,TOPIC38,72,SEX2,CAT2,MARITAL,RESP036,"(18.220833, -66.590149)"
1827437,2018,GU,Guam,Injury,Seatbelt Use,Always or nearly always wears a seat belt?,Yes,Male,Gender,631,...,NaN,BRFSS,CLASS12,TOPIC50,66,SEX1,CAT2,_RFSEAT2,RESP046,"(13.444304, 144.793731)"
1827453,2018,PR,Puerto Rico,Health Status,Overall Health,How is your general health?,Excellent,Female,Gender,435,...,NaN,BRFSS,CLASS08,TOPIC41,72,SEX2,CAT2,GENHLTH,RESP056,"(18.220833, -66.590149)"
1827473,2018,GU,Guam,Demographics,Employment,What is your employment status?,Employed,Male,Gender,399,...,NaN,BRFSS,CLASS05,TOPIC22,66,SEX1,CAT2,EMPLOY1,RESP137,"(13.444304, 144.793731)"

In [35]:
overall_df = obesity_df[obesity_df['Break_Out_Category'].isin(['Overall'])]
overall_df

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,...,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,ResponseID,GeoLocation
0,2012,GU,Guam,Demographics,Age,What is your age?,55-64 years,Overall,Overall,296,...,NaN,BRFSS,CLASS05,Topic02,66,BO1,CAT1,AGE,RESP014,"(13.444304, 144.793731)"
8,2013,GU,Guam,Demographics,Age,What is your age?,55-64 years,Overall,Overall,242,...,NaN,BRFSS,CLASS05,Topic02,66,BO1,CAT1,AGE,RESP014,"(13.444304, 144.793731)"
26,2019,KY,Kentucky,Chronic Health Indicators,Skin Cancer,Ever told you had skin cancer?,Yes,Overall,Overall,768,...,NaN,BRFSS,CLASS03,TOPIC53,21,BO1,CAT1,CHCSCNCR,RESP046,"(37.645970271000465, -84.77497104799966)"
46,2019,KY,Kentucky,Overweight and Obesity (BMI),BMI Categories,Weight classification by Body Mass Index (BMI)...,Overweight (BMI 25.0-29.9),Overall,Overall,2706,...,NaN,BRFSS,CLASS14,TOPIC09,21,BO1,CAT1,_BMI5CAT,RESP040,"(37.645970271000465, -84.77497104799966)"
47,2019,KY,Kentucky,Physical Activity,Exercise,"During the past month, did you participate in ...",No,Overall,Overall,2622,...,NaN,BRFSS,CLASS15,TOPIC23,21,BO1,CAT1,_TOTINDA,RESP054,"(37.645970271000465, -84.77497104799966)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827414,2018,WY,Wyoming,Chronic Health Indicators,Cardiovascular Disease,Ever told you had a heart attack (myocardial i...,Yes,Overall,Overall,272,...,NaN,BRFSS,CLASS03,TOPIC10,56,BO1,CAT1,CVDINFR4,RESP046,"(43.23554134300048, -108.10983035299967)"
1827421,2018,WI,Wisconsin,Oral Health,Teeth Removed,Adults that have had any permanent teeth extra...,No,Overall,Overall,2792,...,NaN,BRFSS,CLASS13,TOPIC57,55,BO1,CAT1,_EXTETH3,RESP054,"(44.39319117400049, -89.81637074199966)"
1827422,2018,UW,All States and DC (median) **,Demographics,Number of Children,How many children live in your household? (var...,Five or more children,Overall,Overall,51,...,NaN,BRFSS,CLASS05,TOPIC39,98,BO1,CAT1,_CHLDCNT,RESP090,NaN
1827463,2018,WI,Wisconsin,Tobacco Use,Smoker Status,Four Level Smoking Status (variable calculated...,Smoke some days,Overall,Overall,209,...,NaN,BRFSS,CLASS17,TOPIC55,55,BO1,CAT1,_SMOKER3,RESP069,"(44.39319117400049, -89.81637074199966)"
1827471,2018,UW,All States and DC (median) **,Oral Health,Teeth Removed,Adults that have had any permanent teeth extra...,No,Overall,Overall,51,...,NaN,BRFSS,CLASS13,TOPIC57,98,BO1,CAT1,_EXTETH3,RESP054,NaN

AttributeError: 'str' object has no attribute 'value_counts'